-- ----------------------------------------------------------------------------
-- Itens e pagamentos de pedidos/orçamentos como tabelas de verdade.
--
-- Hoje pedidos.servico (e orcamentos_formalizados.descricao) guardam, num
-- único texto, a descrição legível dos itens + [OBSERVAÇÕES GERAIS] +
-- [ITENS_JSON] + [PAGAMENTOS] (orçamentos não têm [PAGAMENTOS]). Consequência:
-- não dá pra somar faturamento em SQL (o cálculo é feito no navegador, ver
-- useFinanceiroMetrics.js), não dá pra indexar/filtrar por produto, e
-- id_produto dentro do JSON nunca foi FK de verdade — nunca revalidado, vira
-- referência órfã silenciosa se o produto é excluído do catálogo.
--
-- Esta migração é ADITIVA: cria pedido_itens/pedido_pagamentos/orcamento_itens
-- e alimenta com um backfill à parte (rota temporária, roda uma vez). Não
-- apaga nem altera pedidos.servico/orcamentos_formalizados.descricao — essas
-- colunas continuam sendo gravadas (mirror) enquanto os consumidores fora do
-- escopo desta entrega (PrintLayout, WhatsApp API, resumo de lista) não forem
-- migrados. Reversível: um "drop table" desfaz tudo sem tocar nos dados
-- originais.
--
-- Valores em centavos (inteiro), consistente com pedidos.valor_total,
-- produtos.preco_base etc. (ver valores_centavos_migration.sql) — os JSONs de
-- origem estão em reais formatado BR; a conversão acontece no backfill/no app.
-- ----------------------------------------------------------------------------

create table if not exists public.pedido_itens (
    id bigint generated by default as identity primary key,
    pedido_id bigint not null references public.pedidos(id) on delete cascade,
    produto_id bigint references public.produtos(id) on delete set null,
    ordem integer not null default 0,
    nome text,
    descricao text,
    valor_centavos integer not null default 0,
    valor_original_centavos integer,
    desconto_percentual numeric,
    local_producao text,
    concluido boolean not null default false,
    created_at timestamptz not null default now()
);

create index if not exists idx_pedido_itens_pedido_id on public.pedido_itens(pedido_id);
create index if not exists idx_pedido_itens_produto_id on public.pedido_itens(produto_id);

create table if not exists public.pedido_pagamentos (
    id bigint generated by default as identity primary key,
    pedido_id bigint not null references public.pedidos(id) on delete cascade,
    ordem integer not null default 0,
    forma text not null,
    valor_centavos integer not null default 0,
    parcelas integer,
    instituicao text,
    bandeira text,
    data date,
    vencimento_boleto date,
    boleto_concluido boolean,
    lote_id text,
    created_at timestamptz not null default now()
);

create index if not exists idx_pedido_pagamentos_pedido_id on public.pedido_pagamentos(pedido_id);
create index if not exists idx_pedido_pagamentos_lote_id on public.pedido_pagamentos(lote_id);

create table if not exists public.orcamento_itens (
    id bigint generated by default as identity primary key,
    orcamento_id bigint not null references public.orcamentos_formalizados(id) on delete cascade,
    produto_id bigint references public.produtos(id) on delete set null,
    ordem integer not null default 0,
    nome text,
    descricao text,
    valor_centavos integer not null default 0,
    valor_original_centavos integer,
    desconto_percentual numeric,
    local_producao text,
    created_at timestamptz not null default now()
);

create index if not exists idx_orcamento_itens_orcamento_id on public.orcamento_itens(orcamento_id);
create index if not exists idx_orcamento_itens_produto_id on public.orcamento_itens(produto_id);

-- RLS espelhando pedidos/produtos (rls_and_auth_migration.sql +
-- demo_role_migration.sql): select liberado a qualquer autenticado
-- (inclusive demo), insert/update/delete liberados a qualquer autenticado
-- exceto o papel 'demo'.
alter table public.pedido_itens enable row level security;
alter table public.pedido_pagamentos enable row level security;
alter table public.orcamento_itens enable row level security;

drop policy if exists "pedido_itens_select" on public.pedido_itens;
create policy "pedido_itens_select" on public.pedido_itens for select to authenticated using (true);
drop policy if exists "pedido_itens_insert" on public.pedido_itens;
create policy "pedido_itens_insert" on public.pedido_itens for insert to authenticated with check (nivel_atual() <> 'demo');
drop policy if exists "pedido_itens_update" on public.pedido_itens;
create policy "pedido_itens_update" on public.pedido_itens for update to authenticated using (nivel_atual() <> 'demo') with check (nivel_atual() <> 'demo');
drop policy if exists "pedido_itens_delete" on public.pedido_itens;
create policy "pedido_itens_delete" on public.pedido_itens for delete to authenticated using (nivel_atual() <> 'demo');

drop policy if exists "pedido_pagamentos_select" on public.pedido_pagamentos;
create policy "pedido_pagamentos_select" on public.pedido_pagamentos for select to authenticated using (true);
drop policy if exists "pedido_pagamentos_insert" on public.pedido_pagamentos;
create policy "pedido_pagamentos_insert" on public.pedido_pagamentos for insert to authenticated with check (nivel_atual() <> 'demo');
drop policy if exists "pedido_pagamentos_update" on public.pedido_pagamentos;
create policy "pedido_pagamentos_update" on public.pedido_pagamentos for update to authenticated using (nivel_atual() <> 'demo') with check (nivel_atual() <> 'demo');
drop policy if exists "pedido_pagamentos_delete" on public.pedido_pagamentos;
create policy "pedido_pagamentos_delete" on public.pedido_pagamentos for delete to authenticated using (nivel_atual() <> 'demo');

drop policy if exists "orcamento_itens_select" on public.orcamento_itens;
create policy "orcamento_itens_select" on public.orcamento_itens for select to authenticated using (true);
drop policy if exists "orcamento_itens_insert" on public.orcamento_itens;
create policy "orcamento_itens_insert" on public.orcamento_itens for insert to authenticated with check (nivel_atual() <> 'demo');
drop policy if exists "orcamento_itens_update" on public.orcamento_itens;
create policy "orcamento_itens_update" on public.orcamento_itens for update to authenticated using (nivel_atual() <> 'demo') with check (nivel_atual() <> 'demo');
drop policy if exists "orcamento_itens_delete" on public.orcamento_itens;
create policy "orcamento_itens_delete" on public.orcamento_itens for delete to authenticated using (nivel_atual() <> 'demo');

-- A rota de backfill usa a service role key (bypassa RLS) para popular estas
-- tabelas a partir do texto existente — rodar depois de aplicar esta migração.
